import Question from 'src/app/models/question';
import Quiz from "src/app/models/quiz";
import Prompt from 'src/app/models/prompt';

let orderPrompts:Prompt[]=[
    { step: 1,prompt:"Where are you located?", toPause:true},
    { step: 2,prompt:"Do you have any of the following food allergies?", toPause:false},
    { step: 3,prompt:"Do you follow any of these dietary restrictions?", toPause:false},
    { step: 4,prompt:"How long can you wait to eat?", toPause:false},
    { step: 6,prompt:"Have you eaten food that falls into any of these categories very recently?", toPause:false},
    { step: 7,prompt:"You would describe yourself as*", toPause:false, subPrompt: "Sorry if this question isn't inclusive. Blame science"},
    { step: 8,prompt:"Are you eating alone, or with other people?", toPause:false},
    { step: 9,prompt:"Right now, my mood is most accurately described as…", toPause:true},
    { step: 10,prompt:"I'm pregnant", toPause:false},
    { step: 11,prompt:"Compared to my peers, I had stronger emotional reactions to my grades in school ", toPause:false},
    { step: 12,prompt:"I'm very competative, even when it comes to friendly games, like UNO, Beer pong, or Chardee MacDennis.", toPause:false},
    { step: 13,prompt:"If I went skydiving, its because… ", toPause:false},
    { step: 14,prompt:"I often rewatch my favorite movies, shows, and re-read my favorite books.", toPause:false},
    { step: 15,prompt:"If I moved into a new home, I'd do this before the other.", toPause:false},
    { step: 16,prompt:"If this site gave you a recommendation and you suddenly had no choice but to eat whatever it recommended: would you back-out now, or continue? ", toPause:false, subPrompt: "It would fit within your dietary restrictions and wouldn't be something stupidly disgusting."},

]

let cookPrompts:Prompt[]=[
    { step: 1,prompt:"Do you have any of the following food allergies?", toPause:true},
    { step: 2,prompt:"Do you follow any of these dietary restrictions?", toPause:false},
    { step: 3,prompt:"How long can you wait to eat?", toPause:false},
    { step: 4,prompt:"Do you have time to go an buy additional ingredients you may not have?", toPause:false},
    { step: 5,prompt:"Have you eaten food that falls into any of these categories very recently?", toPause:true},
    { step: 6,prompt:"You would describe yourself as*", toPause:false, subPrompt: "Sorry if this question isn't inclusive. Blame science"},
    { step: 7,prompt:"Are you eating alone, or with other people?", toPause:false},
    { step: 8,prompt:"Right now, my mood is most accurately described as…", toPause:true},
    { step: 9,prompt:"I'm pregnant", toPause:false},
    { step: 10,prompt:"Compared to my peers, I had stronger emotional reactions to my grades in school ", toPause:false},
    { step: 11,prompt:"I'm very competative, even when it comes to friendly games, like UNO, Beer pong, or Chardee MacDennis.", toPause:false},
    { step: 12,prompt:"If I went skydiving, its because… ", toPause:false},
    { step: 13,prompt:"I often rewatch my favorite movies, shows, and re-read my favorite books.", toPause:false},
    { step: 14,prompt:"If I moved into a new home, I'd do this before the other.", toPause:false},
    { step: 15,prompt:"If this site gave you a recommendation and you suddenly had no choice but to eat whatever it recommended: would you back-out now, or continue? ", toPause:false, subPrompt: "It would fit within your dietary restrictions and wouldn't be something stupidly disgusting."},
]

let cookQuestions:Question[]=[
    {step: 1,type:2,label:"Peanuts",cssid: "cook1s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Shellfish",cssid: "cook2s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Milk (Lactose)",cssid: "cook3s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Soy",cssid: "cook4s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Wheat (Gluten)",cssid: "cook5s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Eggs",cssid: "cook6s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:2,label:"Tree Nuts",cssid: "cook7s-1",className: "t-2 cookQ s-1",},
    {step: 1,type:3,label:"Other",cssid: "cook8s-1",className: "t-3 cookQ s-1",},
    {step: 2,type:2,label:"Vegatarian",cssid: "cook9s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:2,label:"Vegan",cssid: "cook10s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:2,label:"Kosher",cssid: "cook11s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:2,label:"Halal",cssid: "cook12s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:2,label:"Pescatarian",cssid: "cook13s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:2,label:"Keto",cssid: "cook14s-2",className: "t-2 cookQ s-2",},
    {step: 2,type:3,label:"Other",cssid: "cook15s-2",className: "t-3 cookQ s-2",},
    {step: 3,type:1,label:"I am on deaths doorstep",choiceid:1,cssid: "cook16s-3",className: "t-1 cookQ s-3",},
    {step: 3,type:1,label:"No more than 30 minutes",choiceid:2,cssid: "cook17s-3",className: "t-1 cookQ s-3",},
    {step: 3,type:1,label:"I could last another hour",choiceid:3,cssid: "cook18s-3",className: "t-1 cookQ s-3",},
    {step: 3,type:1,label:"I got all day",choiceid:4,cssid: "cook19s-3",className: "t-1 cookQ s-3",},
    {step: 3,type:1,label:"I don’t care",choiceid:5,cssid: "cook20s-3",className: "t-1 cookQ s-3",},
    {step: 4,type:1,label:"Yes",choiceid:1,cssid: "cook21s-4",className: "t-1 cookQ s-4",},
    {step: 4,type:1,label:"No ",choiceid:2,cssid: "cook22s-4",className: "t-1 cookQ s-4",},
    {step: 5,type:2,label:"Sandwiches",cssid: "cook23s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Thai",cssid: "cook24s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"American",cssid: "cook25s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Greek",cssid: "cook26s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Seafood",cssid: "cook27s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Mexican",cssid: "cook28s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Pizza",cssid: "cook29s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Italian",cssid: "cook30s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Japanese",cssid: "cook31s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Chinese",cssid: "cook32s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:2,label:"Carribean",cssid: "cook33s-5",className: "t-2 cookQ s-5",},
    {step: 5,type:3,label:"Other",cssid: "cook34s-5",className: "t-3 cookQ s-5",},
    {step: 6,type:1,label:"Male",choiceid:1,cssid: "cook35s-6",className: "t-1 cookQ s-6",},
    {step: 6,type:1,label:"Female",choiceid:2,cssid: "cook36s-6",className: "t-1 cookQ s-6",},
    {step: 6,type:1,label:"Prefer not to answer",choiceid:3,cssid: "cook37s-6",className: "t-1 cookQ s-6",},
    {step: 7,type:1,label:"Alone",choiceid:1,cssid: "cook38s-7",className: "t-1 cookQ s-7",},
    {step: 7,type:1,label:"One, or a couple of others",choiceid:2,cssid: "cook39s-7",className: "t-1 cookQ s-7",},
    {step: 7,type:1,label:"Many people",choiceid:3,cssid: "cook40s-7",className: "t-1 cookQ s-7",},
    {step: 8,type:1,label:"Distressed",choiceid:1,cssid: "cook41s-8",className: "t-1 cookQ s-8",},
    {step: 8,type:1,label:"Anxious",choiceid:2,cssid: "cook42s-8",className: "t-1 cookQ s-8",},
    {step: 8,type:1,label:"Neither of these ",choiceid:3,cssid: "cook43s-8",className: "t-1 cookQ s-8",},
    {step: 9,type:1,label:"Yes ",choiceid:1,cssid: "cook44s-9",className: "t-1 cookQ s-9",},
    {step: 9,type:1,label:"No",choiceid:2,cssid: "cook45s-9",className: "t-1 cookQ s-9",},
    {step: 10,type:1,label:"Yes",choiceid:1,cssid: "cook46s-10",className: "t-1 cookQ s-10",},
    {step: 10,type:1,label:"No",choiceid:2,cssid: "cook47s-10",className: "t-1 cookQ s-10",},
    {step: 11,type:1,label:"Yes",choiceid:1,cssid: "cook48s-11",className: "t-1 cookQ s-11",},
    {step: 11,type:1,label:"No",choiceid:2,cssid: "cook49s-11",className: "t-1 cookQ s-11",},
    {step: 12,type:1,label:"I wanted to experience free-fall",choiceid:1,cssid: "cook50s-12",className: "t-1 cookQ s-12",},
    {step: 12,type:1,label:"I wanted to do something adventurous",choiceid:2,cssid: "cook51s-12",className: "t-1 cookQ s-12",},
    {step: 13,type:1,label:"Yes",choiceid:1,cssid: "cook52s-13",className: "t-1 cookQ s-13",},
    {step: 13,type:1,label:"No",choiceid:2,cssid: "cook53s-13",className: "t-1 cookQ s-13",},
    {step: 14,type:1,label:"Organize, decorate, and clean. ",choiceid:1,cssid: "cook54s-14",className: "t-1 cookQ s-14",},
    {step: 14,type:1,label:"Explore the neighborhood",choiceid:2,cssid: "cook55s-14",className: "t-1 cookQ s-14",},
    {step: 15,type:1,label:"You don't scare me",choiceid:1,cssid: "cook56s-15",className: "t-1 cookQ s-15",},
    {step: 15,type:1,label:"No thanks",choiceid:2,cssid: "cook57s-15",className: "t-1 cookQ s-15"}
]

let orderQuestions:Question[]=[
    {step:1,type:3,label:"Address, State, City, Zip",cssid: "order1s-1",className: "t-3 orderQ s-1",},
    {step:1,type:1,label:"Find me",cssid: "order2s-1",className: "t-1 orderQ s-1",},
    {step: 2,type:2,label:"Peanuts",cssid: "order3s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Shellfish",cssid: "order4s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Milk (Lactose)",cssid: "order5s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Soy",cssid: "order6s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Wheat (Gluten)",cssid: "order7s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Eggs",cssid: "order8s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:2,label:"Tree Nuts",cssid: "order9s-2",className: "t-2 orderQ s-2",},
    {step: 2,type:3,label:"Other",cssid: "order10s-2",className: "t-3 orderQ s-2",},
    {step: 3,type:2,label:"Vegatarian",cssid: "order11s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:2,label:"Vegan",cssid: "order12s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:2,label:"Kosher",cssid: "order13s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:2,label:"Halal",cssid: "order14s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:2,label:"Pescatarian",cssid: "order15s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:2,label:"Keto",cssid: "order16s-3",className: "t-2 orderQ s-3",},
    {step: 3,type:3,label:"Other",cssid: "order17s-3",className: "t-3 orderQ s-3",},
    {step: 4,type:1,label:"I am on deaths doorstep",choiceid:1,cssid: "order18s-4",className: "t-1 orderQ s-4",},
    {step: 4,type:1,label:"No more than 30 minutes",choiceid:2,cssid: "order19s-4",className: "t-1 orderQ s-4",},
    {step: 4,type:1,label:"I could last another hour",choiceid:3,cssid: "order20s-4",className: "t-1 orderQ s-4",},
    {step: 4,type:1,label:"I got all day",choiceid:4,cssid: "order23s-4",className: "t-1 orderQ s-4",},
    {step: 4,type:1,label:"I don’t care",choiceid:5,cssid: "order24s-4",className: "t-1 orderQ s-4",},
    {step: 6,type:2,label:"Sandwiches",cssid: "order25s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Thai",cssid: "order26s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"American",cssid: "order27s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Greek",cssid: "order28s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Seafood",cssid: "order29s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Mexican",cssid: "order30s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Pizza",cssid: "order31s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Italian",cssid: "order32s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Japanese",cssid: "order33s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Chinese",cssid: "order34s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:2,label:"Carribean",cssid: "order35s-6",className: "t-2 orderQ s-6",},
    {step: 6,type:3,label:"Other",cssid: "order36s-6",className: "t-3 orderQ s-6",},
    {step: 7,type:1,label:"Male",choiceid:1,cssid: "order37s-7",className: "t-1 orderQ s-7",},
    {step: 7,type:1,label:"Female",choiceid:2,cssid: "order38s-7",className: "t-1 orderQ s-7",},
    {step: 7,type:1,label:"Prefer not to answer",choiceid:3,cssid: "order39s-7",className: "t-1 orderQ s-7",},
    {step: 8,type:1,label:"Alone",choiceid:1,cssid: "order40s-8",className: "t-1 orderQ s-8",},
    {step: 8,type:1,label:"One, or a couple of others",choiceid:2,cssid: "order41s-8",className: "t-1 orderQ s-8",},
    {step: 8,type:1,label:"Many people",choiceid:3,cssid: "order42s-8",className: "t-1 orderQ s-8",},
    {step: 9,type:1,label:"Distressed",choiceid:1,cssid: "order43s-9",className: "t-1 orderQ s-9",},
    {step: 9,type:1,label:"Anxious",choiceid:2,cssid: "order44s-9",className: "t-1 orderQ s-9",},
    {step: 9,type:1,label:"Neither of these ",choiceid:3,cssid: "order45s-9",className: "t-1 orderQ s-9",},
    {step: 10,type:1,label:"Yes ",choiceid:1,cssid: "order46s-10",className: "t-1 orderQ s-10",},
    {step: 10,type:1,label:"No",choiceid:2,cssid: "order47s-10",className: "t-1 orderQ s-10",},
    {step: 11,type:1,label:"Yes",choiceid:1,cssid: "order48s-11",className: "t-1 orderQ s-11",},
    {step: 11,type:1,label:"No",choiceid:2,cssid: "order49s-11",className: "t-1 orderQ s-11",},
    {step: 12,type:1,label:"Yes",choiceid:1,cssid: "order50s-12",className: "t-1 orderQ s-12",},
    {step: 12,type:1,label:"No",choiceid:2,cssid: "order51s-12",className: "t-1 orderQ s-12",},
    {step: 13,type:1,label:"I wanted to experience free-fall",choiceid:1,cssid: "order52s-13",className: "t-1 orderQ s-13",},
    {step: 13,type:1,label:"I wanted to do something adventurous",choiceid:2,cssid: "order53s-13",className: "t-1 orderQ s-13",},
    {step: 14,type:1,label:"Yes",choiceid:1,cssid: "order54s-14",className: "t-1 orderQ s-14",},
    {step: 14,type:1,label:"No",choiceid:2,cssid: "order55s-14",className: "t-1 orderQ s-14",},
    {step: 15,type:1,label:"Organize, decorate, and clean. ",choiceid:1,cssid: "order56s-15",className: "t-1 orderQ s-15",},
    {step: 15,type:1,label:"Explore the neighborhood",choiceid:2,cssid: "order57s-15",className: "t-1 orderQ s-15",},
    {step: 16,type:1,label:"You don't scare me",choiceid:1,cssid: "order56s-16",className: "t-1 orderQ s-16",},
    {step: 16,type:1,label:"No thanks",choiceid:2,cssid: "order57s-16",className: "t-1 orderQ s-16",},

]

export let orderQuiz:Quiz={
    id:"orderquiz",
    path:2,
    questions:orderQuestions,
    prompts:orderPrompts
    
}
export let cookQuiz:Quiz={
    id:"cookquiz",
    path:1,
    questions:cookQuestions,
    prompts:cookPrompts
}

